inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-factory_bot
  - rubocop-graphql

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/**/*'

Documentation:
  Enabled: false

GraphQL/ObjectDescription:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Naming/MethodParameterName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
